### ISSUE TITLE
I had run all epoch ,but have error

### ISSUE THREAD

**Issue by xiaofei624** [MohsenZand/ObjectBox#16]
Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 625/625 [01:05<00:00, 11.62it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 625/625 [01:05<00:00,  9.56it/s]
Traceback (most recent call last):
  File "train.py", line 470, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "train.py", line 455, in main
    train(FLAGS.hyp, device, callbacks)
  File "train.py", line 414, in train
    callbacks.run('on_train_end', last, best, True, epoch)
  File "/mnt/a/ObjectBox-master/callbacks.py", line 71, in run
    logger['callback'](*args, **kwargs)
  File "/mnt/a/ObjectBox-master/loggers.py", line 126, in on_train_end
    plot_results(file=self.save_dir / 'results.csv')  # save results.png
NameError: name 'plot_results' is not defined

**Comment by MohsenZand** [comment]
'plot_results' was missing. It's added now.
